server:
  replicaCount: 1
  image:
    repository: christiansiegel/zally-server
    tag: e4940e5
  network:
    http:
      servicePort: 8080
      ingress:
        host: zally.apps.baloise.dev
    mgmt:
      servicePort: 7979
  readinessProbe:
    httpGet:
      path: /health
      port: mgmt
  livenessProbe:
    httpGet:
      path: /health
      port: mgmt
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: MANAGEMENT_PORT
    value: '7979'
  - name: TOKEN_INFO_URI
    value: https://url.not.set

frontend:
  replicaCount: 0
  image:
    repository: christiansiegel/zally-ui
    tag: e4940e5
  network:
    http:
      servicePort: 8080
      ingress:
        host: zally-ui.apps.baloise.dev
  env:
  - name: ZALLY_API_URL
    value: https://zally.apps.baloise.dev
