generic:
  image:
    repository: christiansiegel/zally-server
    tag: 490ab4c5
  ports:
    http:
      containerPort: 8000
  ingress:
    enabled: true
    host: zally.apps.origin.baloise.dev
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: MANAGEMENT_PORT
    value: '7979'
  - name: TOKEN_INFO_URI
    value: https://url.not.set

ui:
  image:
    repository: christiansiegel/zally-ui
    tag: 0.1.1
  ingress:
    enabled: true
    host: zally-ui.apps.origin.baloise.dev
  env:
  - name: ZALLY_API_URL
    value: https://zally.apps.origin.baloise.dev
