apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-kaptain
  labels:
    app: {{ template "app.name" . }}-kaptain
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.kaptain.service.type }}
  ports:
    - port: {{ .Values.kaptain.service.port }}
      targetPort: {{ .Values.kaptain.appPort }}
      protocol: TCP
  selector:
    app: {{ template "app.name" . }}-kaptain
    release: {{ .Release.Name }}
